env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
  - eslint-comments
rules:
  react/jsx-filename-extension: 0
  import/prefer-default-export: 0
  "eslint-comments/disable-enable-pair": "error"
  "eslint-comments/no-duplicate-disable": "error"
  "eslint-comments/no-unlimited-disable": "error"
  "eslint-comments/no-unused-disable": "error"
  "eslint-comments/no-unused-enable": "error"
  "eslint-comments/no-use": "error"
