stages:
  - code_quality
  - test
  - build
eslint:
  image: node:16.13.2
  only:
    - staging
    - main
  stage: code_quality
  before_script:
    - npm install
  script:
    - npm eslint -- --ext .jsx,.js src/
unit_tests:
  image: node:16.13.2
  only:
    - staging
    - main
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node:16.13.2
  only:
    - staging
    - main  
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
